[package]
name = "bolt_http"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.56"
either = "1.7.0"
hyper = { version = "0.14.18", features = ["server", "stream", "http1", "http2"] }
typemap = "0.3.3"
