[package]
name = "bolt_url"
version = "0.1.0"
edition = "2021"

[dependencies]
smallvec = "1.7.0"
once_cell = "1.8.0"
aho-corasick = "0.7.18"
lazy_static = "1.4.0"

[dev-dependencies]
criterion = "0.3.5"

[[bench]]
name = "url"
harness = false

