[package]
name = "bolt_fs"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.13.0", features = ["fs", "io-util"] }
tokio-stream = "0.1.8"
smallvec = "1.7.0"
async-trait = "0.1.51"
notify = "4.0.17"
