[package]
name = "bolt_routing"
version = "0.1.0"
edition = "2021"

[dependencies]
aho-corasick = "1.0"
arc-swap = "1.6"
eyre = "0.6"
hashbrown = "0.13"
http = "0.2"
itertools = "0.10"
regex = "1.6"
tower = { version = "0.4", features = ["steer"] }
thiserror = "1.0"
