[package]
name = "bolt_router"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.6.0"
aho-corasick = "0.7.19"
hashbrown = "0.12.3"
tower = "0.4.13"
eyre = "0.6.8"
itertools = "0.10.5"

bolt_service = { path = "../bolt_service" }
